Test memoize min time
tdr-autosync/mi-lib-django_memoize pull request #57
Opened 2024-09-17 00:01 UTC by kartik-gupta28

This change is related to the ticket: https://trader.atlassian.net/browse/MCNG-380

Unhaggle is storing all unnecessary data in a cache. As a result, I'm altering Unhaggle's caching condition so that we may check our memoize decorator, which determines the time limit and whether or not to cache that query.

Any other application that uses this library won't be affected by this change.

Test Case results

![image](https://github.com/user-attachments/assets/e74899fa-479d-4571-b150-2fba9a9d2d2a)

2024-09-17 16:50 UTC, kartik-gupta28 commented
@jhonatandarosa , @4fuss , @danialmalik 
Can I proceed to merge this PR?

2024-09-18 06:07 UTC, danialmalik requested changes

2024-09-18 06:07 UTC, danialmalik commented on memoize/__init__.py
> +    def memoize(self, timeout=DEFAULT_TIMEOUT, min_time=0, make_name=None, unless=None):
lets add this new argument as the last argument. so that if there are any existing calls to memoize with positional args, it doesn't break it.

2024-09-18 06:26 UTC, kartik-gupta28 commented on memoize/__init__.py
> +    def memoize(self, timeout=DEFAULT_TIMEOUT, min_time=0, make_name=None, unless=None):
Done.

2024-09-19 05:43 UTC, danialmalik reviewed
Lets update/add the tests too please.

2024-09-20 05:23 UTC, danialmalik approved these changes

2024-09-20 05:24 UTC, danialmalik commented
Travis is not running on this PR. probably we need to integrate travis with this repo. Could you please connect with infra team to do so?

2024-09-24 15:41 UTC, Kaniabi approved these changes

2024-09-25 06:16 UTC, 4fuss approved these changes

2024-09-25 11:51 UTC, aspd172 commented on memoize/__init__.py
> +    def memoize(self, timeout=DEFAULT_TIMEOUT, make_name=None, unless=None, min_time=0):
this now exceeds the 80 line limit we have for Python code

2024-09-25 11:51 UTC, aspd172 commented on tests/tests.py
> +        assert result_slow_1 == result_slow_2, "Slow function should cache results"
assertions are exceeding line limits

2024-09-25 11:51 UTC, aspd172 commented on tests/tests.py
> +            return random.randrange(0, 100000)
while it's highly unlikely there is a possibility that the test would fail (or in the case of `slow_function` not do as it's supposed to) when the randomizer returns the same value in consecutive calls.

perhaps something like:
```python
        source= (x for x in range(10))
        @self.memoizer.memoize(timeout=10, min_time=0.5)
        def test_function():
            ...
            return next(source)
```

2024-09-26 02:45 UTC, kartik-gupta28 commented on tests/tests.py
> +            return random.randrange(0, 100000)
Fixed

2024-09-26 02:45 UTC, kartik-gupta28 commented on tests/tests.py
> +        assert result_slow_1 == result_slow_2, "Slow function should cache results"
Fixed

2024-09-26 02:46 UTC, kartik-gupta28 commented on memoize/__init__.py
> +    def memoize(self, timeout=DEFAULT_TIMEOUT, make_name=None, unless=None, min_time=0):
Done

2024-09-26 02:46 UTC, merged